---
- name: Create EBS Snapshots
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Get EBS Volume IDs
      ec2_instance_info:
        region: your_aws_region
        filters:
          instance-id: your_instance_id
      register: ec2_info

    - name: Create EBS Snapshots
      ec2_snapshot:
        region: your_aws_region
        volume_id: "{{ item.id }}"
        description: "Snapshot for {{ item.device_name }}"
      with_items: "{{ ec2_info.volumes }}"
