---
- name: Check and Restart Systemd Service
  hosts: your_servers
  become: yes # Run tasks with sudo

  vars:
    service_name: your_systemd_service

  tasks:
    - name: Check the status of the service
      systemd:
        name: "{{ service_name }}"
        state: status
      register: service_status

    - name: Restart the service if it is down
      systemd:
        name: "{{ service_name }}"
        state: restarted
      when: service_status.status == 'inactive'
